# -*- coding: utf-8 -*-
"""Anagram_check

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEHV9872beha2xBu-AMxfpknu1EqHiwF
"""

#anagram
def anagram(word1,word2):
  if sorted(word1)==sorted(word2):
    print("It is Anagram")
  else:
    print("It's not Anagram")

anagram("listen","silents")