# -*- coding: utf-8 -*-
"""Area_of_rectangle

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCcon1EAGykKO8TrHVFOC0_am-n4P3DG
"""

#Arae of rectangle
def rec(w,l):
  return w*l
print(rec(10,10))