# -*- coding: utf-8 -*-
"""Armstrong_number

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VASkcb6drNPIfQpLbYJEgOU3qNQ-PwRX
"""

#armstrong
def is_armstrong(num):
    # Convert number to string to easily get the number of digits (n)
    digits = str(num)
    n = len(digits)

    # Calculate sum of digits raised to power n
    total = sum(int(digit) ** n for digit in digits)

    return total == num

print(is_armstrong(153))  # Returns True