# -*- coding: utf-8 -*-
"""Biggest_of_3_numbers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCcon1EAGykKO8TrHVFOC0_am-n4P3DG
"""

#Voting_eligibility
def biggest(A,B,C):
  if A>B and A<C:
    return "A is Biggest"
  elif B>A and B>C:
    return "B is Biggest"
  elif C>A and C>B:
    return "C is Biggest"
  else:
    return "All 3 Numbers are equall"
print(biggest(42,66,55))