# -*- coding: utf-8 -*-
"""Celsius_Fahrenheit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCcon1EAGykKO8TrHVFOC0_am-n4P3DG
"""

#Celsius → Fahrenheit
def Fahrenheit(celcius):
  return celcius*1.8+32
print(Fahrenheit(42))