# -*- coding: utf-8 -*-
"""Counter_using_global_variable

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCcon1EAGykKO8TrHVFOC0_am-n4P3DG
"""

#Counter using global variable
counter=0
def count():
  global counter
  counter+=1
  print(counter)
count()
count()