# -*- coding: utf-8 -*-
"""encapsulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MqMOvl-prKG7EFSmCuZSPeYa56s1ByNl
"""

#encapsulation
class Payment:

    def pay(self):
        pass


class UPI(Payment):

    def pay(self):
        print("UPI Payment")


class Card(Payment):

    def pay(self):
        print("Card Payment")
u = UPI()
c = Card()

u.pay()
c.pay()