# -*- coding: utf-8 -*-
"""Encapsulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112gLQprgSdIH_dGIMbhDT_RI01YN-69j
"""

#Encapsulation
class Bank:

    def __init__(self):

        self.__balance = 1000

    def get_balance(self):

        return self.__balance

    def set_balance(self, amount):

        if amount >= 0:
            self.__balance = amount
b = Bank()

b.set_balance(5000)

print(b.get_balance())