# -*- coding: utf-8 -*-
"""factorial_of_numbers_using_recursion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCcon1EAGykKO8TrHVFOC0_am-n4P3DG
"""

#factorial of numbers using recursion
def fac(n):
  if n==0:
    return 1
  return n*fac(n-1)
print(fac(n=int(input("Enter a Number"))))