# -*- coding: utf-8 -*-
"""fibonacci

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgDzlcCeCmcUm-COxucc0FIqmHW-288u
"""

#fibonacci
def fib(n):
  if n<=1:
    return n
  return fib(n-1)+fib(n-2)
print(fib(6))