# -*- coding: utf-8 -*-
"""Function_inside_function

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCcon1EAGykKO8TrHVFOC0_am-n4P3DG
"""

#Function inside function example
def fun():
  def fun2():
    print("inner function")
  fun2()
fun()