# -*- coding: utf-8 -*-
"""Inheritance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ybes-jL_UiwisTFJbQsvdNMWqbkyfAWY
"""

#inheritance
class Vehicle:

    def __init__(self, brand):

        self.brand = brand

    def start(self):

        print(self.brand, "started")
class Bus(Vehicle):

    def __init__(self, brand, seats):

        super().__init__(brand)

        self.seats = seats

    def show(self):

        print("Brand:", self.brand)
        print("Seats:", self.seats)
b1 = Bus("Volvo", 40)
b1.start()
b1.show()