# -*- coding: utf-8 -*-
"""lambda_fun

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCcon1EAGykKO8TrHVFOC0_am-n4P3DG
"""

#squares using lamba function
square=lambda x:x**2
print(square(44))