# -*- coding: utf-8 -*-
"""method_overriding

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SpMbMWks9Vtkmrvtq86YJ9CIKyKA4Xsv
"""

#method overriding
class parent():
  def blood(self):
    print("O positive")
class child(parent):
  def blood(self):
    print("A positive")
  def color(self):
    print("white")
c=child()
c.blood()
c.color()