# -*- coding: utf-8 -*-
"""palindrome

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pgIUYWhOqen8YljuuAgtpPiN4IXtoD8
"""

#palindrome
def palindrome(word):
  if word==word[::-1]:
    return("Palindrome")
  else:
    return("Not Palindrome")
print(palindrome(input("Enter a word" )))