# -*- coding: utf-8 -*-
"""Power calculation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCcon1EAGykKO8TrHVFOC0_am-n4P3DG
"""

#Power calculation
def fun(num,pow):
  print(num**pow)
fun(9,2)