# -*- coding: utf-8 -*-
"""Prime_number

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VASkcb6drNPIfQpLbYJEgOU3qNQ-PwRX
"""

import math

def is_prime(n):
    # Prime numbers must be greater than 1
    if n <= 1:
        return False
    # Check divisibility from 2 to sqrt(n)
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Example usage:
number = 29
if is_prime(number):
    print(f"{number} is a prime number.")
else:
    print(f"{number} is not a prime number.")