# -*- coding: utf-8 -*-
"""python_practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17WSsRZANkpxuGwkw-MfDc7DWRM1G5sbN
"""

print("hello")

# even odd
number=int(input())
if number%2==0:
  print("Even Number")
else:
  print("Odd Number")

#Largest of 3 numbers
Number_1=int(input())
Number_2=int(input())
Number_3=int(input())
if Number_1>Number_2 and Number_1>Number_3:
  print(Number_1,"is largest number")
elif Number_2>Number_1 and Number_2>Number_3:
  print(Number_2,"is a largest number")
elif Number_3>Number_1 and Number_3>Number_2:
  print(Number_3,"is a largest number")
else:
  print("All 3 Numbers are equal")

# Multiplication table
Number=int(input())
for i in range(1,11):
  print(Number," * ",i," = ",Number*i)

#ATM balance checker
Balance=1000
while True:
  print("\n===== ATM MENU =====")
  print("1.Check Balance")
  print("2.Withdraw")
  print("3.Deposit")
  print("4.Exit")
  choice=input("Enter the choice: ")
  if choice=="1":
    print("Balane: ",Balance)
  elif choice=="2":
    withdraw_amount=int(input("Enter withdraw_amount: "))
    if withdraw_amount<=Balance:
      print("Take your cash")
      Balance=Balance-withdraw_amount
      print("Remaining Balance: ",Balance)
    else:
      print("you don't have enogh balance")
  elif choice=="3":
    Deposit_amount=int(input("Enter Deposit amount: "))
    Balance=Balance+Deposit_amount
    print("Total_Balance: ",Balance)
  elif choice=="4":
    print("Exit Cancel the transaction")
    break
  else:
    print("Invalid choice")

#Simple calculator
Number_1=int(input("Enter a 1st number: "))
Number_2=int(input("Enter a 2nd number: "))
operator=input()
if operator=="+":
  print(Number_1+Number_2)
elif operator=="-":
  print(Number_1-Number_2)
elif operator=="*":
  print(Number_1*Number_2)
elif operator=="/":
  print(Number_1/Number_2)
elif operator=="%":
  print(Number_1%Number_2)