# -*- coding: utf-8 -*-
"""Reverse_a_string

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEHV9872beha2xBu-AMxfpknu1EqHiwF
"""

#reverse a string
def rev(string):
  rev_str=""
  for i in string:
    rev_str=i+rev_str
  print(rev_str)
rev("listen")