# -*- coding: utf-8 -*-
"""Sum_of_even_numbers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCcon1EAGykKO8TrHVFOC0_am-n4P3DG
"""

#Sum of even numbers
def fun(num):
  total=0
  for i in range(1,num+1):
    if i%2==0:
      total+=i
  print(total)
fun(9)