# -*- coding: utf-8 -*-
"""sum_of_numbers_using_recursion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCcon1EAGykKO8TrHVFOC0_am-n4P3DG
"""

#sum of numbers using recursion
def add(n):
  if n==0:
    return n
  return n+add(n-1)
print(add(n=int(input("Enter a Number"))))