# -*- coding: utf-8 -*-
"""table

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgDzlcCeCmcUm-COxucc0FIqmHW-288u
"""

#table
n=int(input("Enter a Number: "))
for i in range(1,11):
    print(n," * ",i," = ",n*i)