# -*- coding: utf-8 -*-
"""target_sum

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ybes-jL_UiwisTFJbQsvdNMWqbkyfAWY
"""

#target_sum
def tar_sum(n,target):
  for i in range(len(n)):
    for j in range(len(n)):
      if n[i]+n[j]==target:
        return i,j
print(tar_sum([1,2,3,4,5],7))