# -*- coding: utf-8 -*-
"""Voting_eligibility

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCcon1EAGykKO8TrHVFOC0_am-n4P3DG
"""

#Voting_eligibility
def eligible(age):
  if age>=0:
    return "Eligible for voting"
  else:
    return "Not Eligible for voting"
print(eligible(42))